const Section = ({ id, title, children }: { id: string; title: string; children: React.ReactNode }) => <section id={id} className="scroll-mt-20 bg-[#161b22] border border-[#21262d] rounded-lg p-5"><h2 className="font-mono text-lg text-slate-100 mb-3">{title}</h2><div className="space-y-3 text-sm leading-6 text-slate-300">{children}</div></section>;
const Code = ({ children }: { children: React.ReactNode }) => <code className="text-blue-300 bg-[#0d1117] px-1 py-0.5 rounded">{children}</code>;
const Row = ({ name, meaning }: { name: string; meaning: string }) => <tr className="border-t border-[#30363d]"><td className="p-2 font-mono text-blue-300">{name}</td><td className="p-2 text-slate-300">{meaning}</td></tr>;

export default function DocumentationPage() {
  const links = [['overview','Overview'],['architecture','Architecture'],['data','Data sources'],['calculations','Calculations'],['risk','Risk engine'],['ensemble','Probability'],['ai','AI features'],['learning','Forecast learning'],['tools','Decision tools'],['storage','Storage & privacy'],['configuration','Configuration'],['limits','Limitations'],['deployment','Deployment']];
  return <div className="min-h-screen bg-[#0d1117] text-slate-200"><header className="sticky top-0 z-20 border-b border-[#21262d] bg-[#0d1117]/95"><div className="max-w-6xl mx-auto px-4 py-3 flex justify-between items-center"><div><h1 className="font-mono font-semibold">WeatherOps Documentation</h1><p className="text-[10px] font-mono text-slate-500">Prescott and Daytona Beach campus weather intelligence</p></div><a href="/" className="px-3 py-1.5 text-xs font-mono border border-[#30363d] rounded hover:bg-[#21262d]">← Dashboard</a></div></header><div className="max-w-6xl mx-auto px-4 py-6 grid lg:grid-cols-[210px_1fr] gap-6"><aside className="hidden lg:block"><nav className="sticky top-20 space-y-1">{links.map(([id,label]) => <a key={id} href={`#${id}`} className="block text-xs font-mono text-slate-500 hover:text-blue-300 py-1.5">{label}</a>)}</nav></aside><main className="space-y-5">
    <Section id="overview" title="Overview"><p>WeatherOps is a fixed two-campus operational weather dashboard for Embry-Riddle locations in Prescott, Arizona, and Daytona Beach, Florida. It combines deterministic forecasts, NWS alerts, ensemble probabilities, facilities-oriented calculations, an Ollama-powered briefing, and decision-support tools.</p><p>WeatherOps is advisory. It does not replace official warnings, emergency management decisions, field observations, equipment controls, or occupational-safety requirements.</p></Section>
    <Section id="architecture" title="Architecture"><p>The browser loads each campus from <Code>/api/weather</Code> and <Code>/api/alerts</Code>. Server routes retrieve upstream information, normalize units, calculate metrics, and return typed JSON. The dashboard separately calls <Code>/api/ensemble</Code> for probabilistic guidance and <Code>/api/ai</Code> for briefing and chatbot responses.</p><table className="w-full text-xs"><tbody><Row name="app/page.tsx" meaning="Dashboard orchestration and fixed campus configuration."/><Row name="lib/weather.ts" meaning="Forecast retrieval, hourly/daily processing, psychrometrics, and risk profiles."/><Row name="lib/calculations.ts" meaning="Unit conversions, degree days, wet bulb, enthalpy, and scoring helpers."/><Row name="app/api/ai" meaning="Server-only Ollama connection; credentials never enter browser code."/><Row name="components/" meaning="Independent dashboard panels, tables, charts, map, and decision tools."/></tbody></table></Section>
    <Section id="data" title="Data sources"><ul className="list-disc pl-5 space-y-1"><li><b>Open-Meteo Forecast API:</b> current, hourly, and seven-day deterministic weather.</li><li><b>Open-Meteo Historical API:</b> season-to-date metrics and forecast verification.</li><li><b>Open-Meteo Ensemble API:</b> NOAA GFS ensemble members used for threshold probabilities and percentile ranges.</li><li><b>National Weather Service:</b> active U.S. watches, warnings, and advisories.</li><li><b>RainViewer:</b> radar-frame overlay and animation.</li><li><b>OpenStreetMap:</b> standard map tiles and geographic context.</li></ul><p>Forecasts are cached for 30 minutes, ensemble guidance for one hour, historical verification for 24 hours, NWS alerts for five minutes, and geocoding code remains in the repository but is no longer exposed in the dashboard.</p></Section>
    <Section id="calculations" title="Weather and energy calculations"><table className="w-full text-xs"><tbody><Row name="Wet bulb" meaning="Calculated for every hourly temperature/RH pair with the Stull approximation; daily extrema come from coincident hourly values."/><Row name="Enthalpy" meaning="Moist-air enthalpy in BTU/lb using dry-bulb temperature, humidity ratio, and surface pressure."/><Row name="Dew point" meaning="Magnus approximation, displayed in Fahrenheit."/><Row name="HDD/CDD" meaning="Daily mean temperature from forecast high and low at bases 60°F, 65°F, and 70°F."/><Row name="Daily precipitation" meaning="Sum of hourly preceding-period precipitation through the current local forecast time."/><Row name="GHI" meaning="Daily shortwave radiation converted from MJ/m² to kWh/m²."/><Row name="ET₀" meaning="FAO-56 reference evapotranspiration supplied by Open-Meteo."/></tbody></table></Section>
    <Section id="risk" title="Explainable risk engine"><p>Risk scores are deterministic and calculated before AI sees the data. Each score includes evidence, timing, severity, and suggested review actions. Severity bands are low below 35, moderate from 35–59, high from 60–79, and extreme at 80 or above.</p><ul className="list-disc pl-5"><li>Cooling demand combines high temperature and wet bulb.</li><li>Heat stress emphasizes maximum coincident hourly wet bulb.</li><li>Heavy rain uses seven-day accumulation, wettest-day total, and precipitation duration.</li><li>Wind evaluates daily maximum sustained wind.</li><li>Freeze evaluates minimum forecast temperature.</li><li>Condensation uses maximum dew point as an outdoor moisture indicator.</li><li>Thunderstorm risk uses forecast weather codes and defers to NWS/radar for operational decisions.</li><li>Fire weather screens minimum RH and wind; it is not an official Red Flag determination.</li></ul></Section>
    <Section id="ensemble" title="Ensemble probability"><p>The dashboard requests NOAA GFS ensemble members. For each day, it counts the share of valid members crossing fixed thresholds: minimum temperature at or below 32°F, precipitation at or above 1 inch, wind or gust at or above 35 mph, and wet bulb at or above 78°F.</p><p>The displayed probability is <Code>members crossing threshold ÷ valid members × 100</Code>. Temperature ranges show 10th and 90th percentiles. These are model probabilities, not guarantees, and do not incorporate every source of forecast uncertainty.</p></Section>
    <Section id="ai" title="AI briefing and chatbot"><p>Ollama Cloud with <Code>gpt-oss:20b</Code> generates audience-specific briefings and answers questions. The selected audience can be Facilities Leadership, Energy Manager, Grounds, Public Safety, or Maintenance Supervisors.</p><p>The server sends compact current conditions, forecasts, calculated risks, NWS alerts, the user question, and the audience. The prompt requires the model to use supplied facts, cite dates and values, distinguish forecasts from official warnings, and say when data is unavailable. AI does not calculate risk scores or alter weather observations.</p><p>If Ollama is missing or a briefing response cannot be parsed, the dashboard uses a deterministic rule-based briefing. Chatbot questions require a configured Ollama key.</p></Section>
    <Section id="learning" title="Forecast preservation and verification"><p>The browser retains up to 60 forecast snapshots, no more than one every six hours. The latest snapshot supports change detection for temperature, precipitation, and risk categories. After forecast dates expire, the dashboard queries historical observations and calculates mean absolute error for daily high, daily low, and precipitation.</p><p>This is browser-local learning: clearing site storage, changing browsers, or changing devices resets the history. It evaluates forecast skill but does not yet retrain or reweight the upstream weather model.</p></Section>
    <Section id="tools" title="Decision-support tools"><p><b>Maintenance Window Optimizer:</b> screens hourly temperature, humidity, precipitation, wind, and gusts against editable code-defined limits for roof inspection, painting, crane/lift work, grounds work, and drone surveys. It returns qualifying windows of at least two consecutive hours.</p><p><b>Event Weather Planner:</b> screens a selected campus date and hour for rain, gust, humid-heat, and freeze thresholds and displays the underlying hourly values. Users must still review NWS alerts, radar, venue conditions, and campus authority.</p></Section>
    <Section id="storage" title="Storage, privacy, and security"><ul className="list-disc pl-5"><li>Forecast snapshots are stored in browser <Code>localStorage</Code>.</li><li>No utility, building, occupancy, or personally identifiable data is used.</li><li>The Ollama API key exists only as a server environment variable.</li><li><Code>.env</Code> and <Code>.env.local</Code> are excluded by <Code>.gitignore</Code>.</li><li>Questions and loaded weather context are transmitted to the configured Ollama endpoint when the chatbot is used.</li></ul></Section>
    <Section id="configuration" title="Configuration"><p>Required AI environment variables:</p><pre className="bg-[#0d1117] border border-[#30363d] rounded p-3 text-xs text-blue-300 overflow-x-auto">OLLAMA_BASE_URL=https://ollama.com/api{`\n`}OLLAMA_API_KEY=your_secret_key{`\n`}OLLAMA_MODEL=gpt-oss:20b</pre><p>Fixed campuses are defined by <Code>DEFAULT_LOC1</Code> and <Code>DEFAULT_LOC2</Code> in <Code>app/page.tsx</Code>. Activity limits are in <Code>components/DecisionToolsPanel.tsx</Code>. Risk formulas are in <Code>lib/weather.ts</Code>.</p></Section>
    <Section id="limits" title="Known limitations"><ul className="list-disc pl-5"><li>Weather models may miss localized storms, terrain effects, and convective timing.</li><li>NWS alerts cover U.S. coordinates only and may have issuance or API delays.</li><li>Radar imagery can be delayed or temporarily unavailable.</li><li>Forecast skill history is browser-specific and initially has no verified days.</li><li>Ensemble probabilities reflect one model family rather than a calibrated multi-model blend.</li><li>Wet bulb is not identical to WBGT and must not be treated as an occupational exposure determination.</li><li>Risk thresholds are screening aids, not adopted campus policy.</li><li>AI output can still be incomplete or poorly phrased; supporting data and official sources remain authoritative.</li></ul></Section>
    <Section id="deployment" title="Local development and deployment"><pre className="bg-[#0d1117] border border-[#30363d] rounded p-3 text-xs text-blue-300">npm install{`\n`}npm run dev{`\n`}npm run build</pre><p>For Vercel, connect the GitHub repository, configure the three Ollama variables, and deploy. Never put the API key in source code, the ZIP, or a public GitHub commit. The production build must pass Next.js compilation, linting, and TypeScript validation.</p></Section>
  </main></div></div>;
}
