'use client';
import { useEffect, useState } from 'react';
import type { Coordinates, EnsembleData } from '@/types';

const riskColor = (p: number) => p >= 70 ? 'text-red-300' : p >= 40 ? 'text-orange-300' : p >= 20 ? 'text-yellow-300' : 'text-slate-500';
export default function EnsemblePanel({ locations }: { locations: Coordinates[] }) {
  const [data, setData] = useState<Array<EnsembleData | null>>([null, null]); const [errors, setErrors] = useState<string[]>([]);
  useEffect(() => { Promise.all(locations.map(l => fetch(`/api/ensemble?lat=${l.lat}&lon=${l.lon}&name=${encodeURIComponent(l.name)}`).then(async r => { const x = await r.json(); if (!r.ok) throw new Error(x.error); return x; }))).then(setData).catch(e => setErrors([e.message])); }, [locations]);
  return <div className="bg-[#161b22] border border-[#21262d] rounded-lg overflow-hidden"><div className="px-4 py-3 border-b border-[#21262d]"><div className="text-[10px] text-slate-500 font-mono uppercase tracking-widest">Probabilistic Forecast</div><p className="text-xs text-slate-400 mt-1">GFS ensemble-member probabilities and 10th–90th percentile temperature ranges</p></div>{errors.length > 0 && <p className="p-4 text-xs text-red-400">{errors[0]}</p>}<div className="grid xl:grid-cols-2 divide-x divide-[#21262d]">{data.map((d, index) => <div key={locations[index].name} className="overflow-x-auto p-3"><h3 className="text-xs font-mono text-slate-300 mb-2">{locations[index].name}</h3>{!d ? <p className="text-xs text-slate-500 animate-pulse">Loading ensemble forecast…</p> : <table className="w-full text-[11px] font-mono"><thead className="text-slate-500"><tr><th className="text-left py-1">Date</th><th>Freeze</th><th>Rain ≥1″</th><th>Wind ≥35</th><th>WB ≥78</th><th>Low range</th><th>High range</th></tr></thead><tbody>{d.daily.map(day => <tr key={day.date} className="border-t border-[#21262d]"><td className="py-1.5 text-slate-300">{new Date(day.date + 'T12:00:00').toLocaleDateString('en-US', { weekday: 'short', month: 'numeric', day: 'numeric' })}</td>{[day.freezeProbability, day.heavyRainProbability, day.highWindProbability, day.humidHeatProbability].map((p, i) => <td key={i} className={`text-center ${riskColor(p)}`}>{p}%</td>)}<td className="text-center text-slate-400">{day.tempLowP10F}–{day.tempLowP90F}°</td><td className="text-center text-slate-400">{day.tempHighP10F}–{day.tempHighP90F}°</td></tr>)}</tbody></table>}</div>)}</div><div className="px-4 py-2 border-t border-[#21262d] text-[10px] text-slate-600">Probabilities are the share of ensemble members crossing each threshold, not guarantees. Member count is shown in the API response.</div></div>;
}
