'use client';
import { useEffect, useState } from 'react';
import type { WeatherData } from '@/types';

type DayPoint = { date: string; maxF: number; minF: number; rainIn: number; risk: string };
type Snapshot = { savedAt: number; locations: Record<string, DayPoint[]> };
type Change = { location: string; date: string; message: string; important: boolean };
type Skill = { location: string; days: number; highMae: number; lowMae: number; rainMae: number };
const KEY = 'weatherops_forecast_history_v3';

export default function ForecastChangePanel({ weather }: { weather: WeatherData[] }) {
  const [changes, setChanges] = useState<Change[]>([]); const [priorTime, setPriorTime] = useState<number | null>(null); const [skill, setSkill] = useState<Skill[]>([]);
  useEffect(() => {
    const current: Snapshot = { savedAt: Date.now(), locations: Object.fromEntries(weather.map(w => [w.location.name, w.daily.map(d => ({ date: d.date, maxF: d.tempMaxF, minF: d.tempMinF, rainIn: d.precipInches, risk: d.peakLoadRisk }))])) };
    try { const history: Snapshot[] = JSON.parse(localStorage.getItem(KEY) ?? '[]'); const prior = history.at(-1) ?? null;
      if (prior) { setPriorTime(prior.savedAt); const found: Change[] = []; for (const w of weather) for (const d of w.daily) { const p = prior.locations[w.location.name]?.find(x => x.date === d.date); if (!p) continue; const t = d.tempMaxF - p.maxF; const rain = d.precipInches - p.rainIn;
        if (Math.abs(t) >= 3) found.push({ location: w.location.name, date: d.dateLabel, message: `High-temperature forecast ${t > 0 ? 'increased' : 'decreased'} ${Math.abs(t).toFixed(1)}°F`, important: Math.abs(t) >= 6 });
        if (Math.abs(rain) >= .2) found.push({ location: w.location.name, date: d.dateLabel, message: `Precipitation forecast ${rain > 0 ? 'increased' : 'decreased'} ${Math.abs(rain).toFixed(2)} in`, important: Math.abs(rain) >= .75 });
        if (p.risk !== d.peakLoadRisk) found.push({ location: w.location.name, date: d.dateLabel, message: `Weather load-risk category changed from ${p.risk} to ${d.peakLoadRisk}`, important: ['high','extreme'].includes(d.peakLoadRisk) }); } setChanges(found.slice(0, 12)); }
      const lastAge = history.at(-1) ? Date.now() - history.at(-1)!.savedAt : Infinity; if (lastAge > 6 * 3600000) localStorage.setItem(KEY, JSON.stringify([...history, current].slice(-60)));
      const today = new Date().toISOString().slice(0, 10); const pastDates = Array.from(new Set(history.flatMap(s => Object.values(s.locations).flat().map(d => d.date)).filter(d => d < today))).sort().slice(-30);
      if (pastDates.length) Promise.all(weather.map(async w => { const r = await fetch(`/api/verification?lat=${w.location.lat}&lon=${w.location.lon}&start=${pastDates[0]}&end=${pastDates.at(-1)}`); if (!r.ok) return null; const actual = await r.json(); const pairs = pastDates.map(date => { const forecast = history.find(s => s.locations[w.location.name]?.some(d => d.date === date))?.locations[w.location.name]?.find(d => d.date === date); const i = Array.isArray(actual.time) ? actual.time.indexOf(date) : -1; return forecast && i >= 0 ? { forecast, high: actual.temperature_2m_max[i], low: actual.temperature_2m_min[i], rain: actual.precipitation_sum[i] } : null; }).filter(Boolean) as Array<{forecast: DayPoint; high:number; low:number; rain:number}>; if (!pairs.length) return null; const avg = (a:number[]) => a.reduce((x,y)=>x+y,0)/a.length; return { location: w.location.name, days: pairs.length, highMae: avg(pairs.map(p=>Math.abs(p.forecast.maxF-p.high))), lowMae: avg(pairs.map(p=>Math.abs(p.forecast.minF-p.low))), rainMae: avg(pairs.map(p=>Math.abs(p.forecast.rainIn-p.rain))) }; })).then(x => setSkill(x.filter(Boolean) as Skill[]));
    } catch { /* browser history is optional */ }
  }, [weather]);
  return <div className="bg-[#161b22] border border-[#21262d] rounded-lg p-4"><div className="flex justify-between mb-3"><div><div className="text-[10px] text-slate-500 font-mono uppercase tracking-widest">Forecast Learning & Change Detection</div><p className="text-xs text-slate-400 mt-1">Retains up to 60 browser snapshots and verifies expired forecasts against historical observations</p></div>{priorTime && <span className="text-[10px] font-mono text-slate-600">Compared with {new Date(priorTime).toLocaleString()}</span>}</div>{skill.length > 0 && <div className="grid md:grid-cols-2 gap-2 mb-3">{skill.map(s => <div key={s.location} className="border border-blue-900 bg-blue-950/10 rounded p-2 text-xs"><span className="text-blue-300">{s.location.split(',')[0]} forecast skill ({s.days} days)</span><span className="text-slate-400 ml-2">High MAE {s.highMae.toFixed(1)}°F · Low MAE {s.lowMae.toFixed(1)}°F · Rain MAE {s.rainMae.toFixed(2)} in</span></div>)}</div>}{!priorTime ? <p className="text-xs text-slate-500">Baseline saved. Changes and skill metrics appear as forecast history accumulates.</p> : changes.length === 0 ? <p className="text-xs text-emerald-400">No material forecast changes detected.</p> : <div className="grid md:grid-cols-2 gap-2">{changes.map((c, i) => <div key={i} className={`rounded border px-3 py-2 ${c.important ? 'border-orange-800 bg-orange-950/20' : 'border-[#30363d] bg-[#0d1117]'}`}><p className="text-[10px] font-mono text-slate-500">{c.location.split(',')[0]} · {c.date}</p><p className="text-xs text-slate-300 mt-1">{c.message}</p></div>)}</div>}</div>;
}
