'use client';
import { useEffect, useMemo, useState } from 'react';
import type { AlertsData, WeatherData } from '@/types';
import OperationsBriefingPanel from '@/components/OperationsBriefingPanel';

const LOCS=[{lat:34.54,lon:-112.4685,name:'Prescott, Arizona, US'},{lat:29.2108,lon:-81.0228,name:'Daytona Beach, Florida, US'}];
type Tab='overview'|'hvac'|'moisture'|'solar'|'context';
type Normal={normal:{hdd:number;cdd:number;rain:number;ghi:number;et0:number};years:Array<{year:number;hdd:number;cdd:number;rain:number;ghi:number;et0:number}>};
const sum=(x:number[])=>x.reduce((a,b)=>a+b,0); const clamp=(n:number)=>Math.max(0,Math.min(100,n));

export default function EnergyPage(){
 const [weather,setWeather]=useState<WeatherData[]>([]); const [alerts,setAlerts]=useState<Array<AlertsData|null>>([]); const [normals,setNormals]=useState<Array<Normal|null>>([null,null]); const [tab,setTab]=useState<Tab>('overview'); const [campus,setCampus]=useState(0); const [pvKw,setPvKw]=useState(1000); const [pr,setPr]=useState(.8); const [loading,setLoading]=useState(true);
 useEffect(()=>{Promise.all(LOCS.map(async l=>{const [w,a]=await Promise.all([fetch(`/api/weather?lat=${l.lat}&lon=${l.lon}&name=${encodeURIComponent(l.name)}`).then(r=>r.json()),fetch(`/api/alerts?lat=${l.lat}&lon=${l.lon}&name=${encodeURIComponent(l.name)}`).then(r=>r.ok?r.json():null)]);return {w,a};})).then(rows=>{const ws=rows.map(r=>r.w);setWeather(ws);setAlerts(rows.map(r=>r.a));return Promise.all(LOCS.map((l,i)=>fetch(`/api/normals?lat=${l.lat}&lon=${l.lon}&dates=${ws[i].daily.map((d:{date:string})=>d.date).join(',')}`).then(r=>r.ok?r.json():null)));}).then(setNormals).finally(()=>setLoading(false));},[]);
 const m=useMemo(()=>weather.map(w=>{const scored=w.hourly.map(h=>{const sensible=clamp((h.tempF-65)*2.2+h.ghiWm2/22);const latent=clamp((h.dewPointF-55)*3+(h.enthalpyBtu-28)*2);const heat=clamp((65-h.tempF)*3);return{...h,sensible,latent,cooling:clamp(sensible*.55+latent*.45),heating:heat};});const peak=scored.reduce((a,b)=>b.cooling>a.cooling?b:a,scored[0]);const economizer=scored.filter(h=>h.tempF>=45&&h.tempF<=65&&h.enthalpyBtu<=28&&h.dewPointF<=55).length;const dew70=scored.filter(h=>h.dewPointF>=70).length;const enth35=scored.filter(h=>h.enthalpyBtu>=35).length;const wb75=scored.filter(h=>h.wetBulbF>=75).length;const sensibleAvg=sum(scored.map(h=>h.sensible))/scored.length;const latentAvg=sum(scored.map(h=>h.latent))/scored.length;const ghi=sum(w.daily.map(d=>d.ghiDailyKwh));const et0=sum(w.daily.map(d=>d.et0Mm));const rainMm=sum(w.daily.map(d=>d.precipInches))*25.4;return{scored,peak,economizer,dew70,enth35,wb75,dominant:sensibleAvg>=latentAvg?'Sensible':'Latent',ghi,et0,rainMm,deficit:Math.max(0,et0-rainMm),hdd:sum(w.daily.map(d=>d.hdd65)),cdd:sum(w.daily.map(d=>d.cdd65))};}),[weather]);
 if(loading||weather.length<2||m.length<2)return <div className="min-h-screen bg-[#0d1117] text-slate-400 flex items-center justify-center font-mono">Building weather-driven energy outlook…</div>;
 const x=m[campus], n=normals[campus]?.normal; const pct=(v:number,b?:number)=>b?((v-b)/b*100):0; const cards=[['Peak cooling stress',`${Math.round(x.peak.cooling)}/100`],['Peak window',new Date(x.peak.time).toLocaleString('en-US',{weekday:'short',hour:'numeric'})],['Economizer opportunity',`${x.economizer} hr`],['Load character',x.dominant]];
 return <div className="min-h-screen bg-[#0d1117] text-slate-200"><header className="sticky top-0 z-20 border-b border-[#21262d] bg-[#0d1117]"><div className="max-w-screen-2xl mx-auto px-4 py-3 flex justify-between items-center"><div><h1 className="font-mono font-semibold">Weather-Driven Energy Outlook</h1><p className="text-[10px] text-slate-500 font-mono">HVAC pressure · moisture · economizer · solar · water · historical context</p></div><div className="flex gap-2"><a href="/" className="px-3 py-1.5 border border-[#30363d] rounded text-xs">Dashboard</a><a href="/documentation" className="px-3 py-1.5 border border-[#30363d] rounded text-xs">Documentation</a></div></div></header><main className="max-w-screen-2xl mx-auto p-4 sm:p-6 space-y-5"><div className="flex flex-wrap justify-between gap-3"><div className="flex gap-1">{(['overview','hvac','moisture','solar','context'] as Tab[]).map(t=><button key={t} onClick={()=>setTab(t)} className={`px-3 py-2 rounded border text-xs font-mono capitalize ${tab===t?'border-blue-600 bg-blue-950/30 text-blue-300':'border-[#30363d] text-slate-500'}`}>{t}</button>)}</div><select value={campus} onChange={e=>setCampus(Number(e.target.value))} className="bg-[#161b22] border border-[#30363d] rounded px-3 py-2 text-xs"><option value={0}>Prescott</option><option value={1}>Daytona Beach</option></select></div>
 {tab==='overview'&&<><div className="grid md:grid-cols-4 gap-3">{cards.map(([a,b])=><div key={a} className="bg-[#161b22] border border-[#21262d] rounded p-4"><p className="text-[10px] uppercase tracking-widest text-slate-500 font-mono">{a}</p><p className="text-xl text-slate-100 mt-2">{b}</p></div>)}</div><div className="bg-[#161b22] border border-[#21262d] rounded p-4"><h2 className="text-xs font-mono text-slate-400 uppercase tracking-widest">Energy management interpretation</h2><p className="text-sm mt-3 text-slate-300">{x.dominant} cooling conditions dominate the seven-day outlook. The highest weather-driven cooling pressure occurs {new Date(x.peak.time).toLocaleString()} with {x.peak.tempF}°F dry bulb, {x.peak.wetBulbF}°F wet bulb, {x.peak.enthalpyBtu} BTU/lb enthalpy and {x.peak.ghiWm2} W/m² solar radiation. Review schedules and equipment readiness; this is not a forecast of actual campus kW.</p></div><OperationsBriefingPanel weather={weather} alerts={alerts} initialRole="Energy manager"/></>}
 {tab==='hvac'&&<><div className="grid md:grid-cols-3 gap-3"><Metric label="7-day CDD65" value={x.cdd.toFixed(1)}/><Metric label="7-day HDD65" value={x.hdd.toFixed(1)}/><Metric label="Economizer opportunity" value={`${x.economizer} hours`}/></div><Heatmap hours={x.scored}/><div className="bg-[#161b22] border border-[#21262d] rounded p-4 text-xs text-slate-400">Economizer screening requires 45–65°F outdoor temperature, enthalpy ≤28 BTU/lb and dew point ≤55°F. Actual availability depends on equipment, controls, indoor conditions and sequences.</div></>}
 {tab==='moisture'&&<div className="grid md:grid-cols-3 gap-3"><Metric label="Dew-point hours ≥70°F" value={`${x.dew70} hr`}/><Metric label="Enthalpy hours ≥35 BTU/lb" value={`${x.enth35} hr`}/><Metric label="Wet-bulb hours ≥75°F" value={`${x.wb75} hr`}/><div className="md:col-span-3 bg-[#161b22] border border-[#21262d] rounded p-4 text-sm text-slate-300">{x.dominant==='Latent'?'Outdoor moisture is the stronger cooling-pressure signal. Prioritize humidity control, outdoor-air sequences and condensation monitoring.':'Temperature and solar gain are stronger than moisture in this outlook. Overnight outdoor conditions may provide operational opportunities where systems permit.'}</div></div>}
 {tab==='solar'&&<div className="grid lg:grid-cols-2 gap-4"><div className="bg-[#161b22] border border-[#21262d] rounded p-4"><h2 className="text-xs font-mono uppercase text-slate-500">PV resource estimate</h2><div className="grid grid-cols-2 gap-2 mt-3"><label className="text-xs">Installed DC kW<input type="number" value={pvKw} onChange={e=>setPvKw(Number(e.target.value))} className="block w-full mt-1 bg-[#0d1117] border border-[#30363d] rounded p-2"/></label><label className="text-xs">Performance ratio<input type="number" step=".01" value={pr} onChange={e=>setPr(Number(e.target.value))} className="block w-full mt-1 bg-[#0d1117] border border-[#30363d] rounded p-2"/></label></div><p className="text-2xl mt-4">{(x.ghi*pvKw*pr).toLocaleString(undefined,{maximumFractionDigits:0})} kWh</p><p className="text-[10px] text-slate-600 mt-1">Simplified 7-day estimate: GHI × DC capacity × performance ratio.</p></div><div className="bg-[#161b22] border border-[#21262d] rounded p-4"><h2 className="text-xs font-mono uppercase text-slate-500">Irrigation weather balance</h2><p className="text-sm mt-3">ET₀: {x.et0.toFixed(1)} mm · precipitation: {x.rainMm.toFixed(1)} mm</p><p className="text-2xl mt-3">{x.deficit.toFixed(1)} mm deficit</p><p className="text-[10px] text-slate-600 mt-1">Preliminary weather balance only; effective precipitation, soil, vegetation and irrigation efficiency are not modeled.</p></div></div>}
 {tab==='context'&&<div className="grid md:grid-cols-2 gap-4"><Context name="CDD65" current={x.cdd} normal={n?.cdd}/><Context name="HDD65" current={x.hdd} normal={n?.hdd}/><Context name="Precipitation (in)" current={x.rainMm/25.4} normal={n?.rain}/><Context name="GHI (kWh/m²)" current={x.ghi} normal={n?.ghi}/><div className="md:col-span-2 text-xs text-slate-500">Normal values are averages for the same seven calendar dates across the previous ten complete years. Difference: CDD {pct(x.cdd,n?.cdd).toFixed(0)}% · HDD {pct(x.hdd,n?.hdd).toFixed(0)}% · GHI {pct(x.ghi,n?.ghi).toFixed(0)}%.</div></div>}
 </main></div>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="bg-[#161b22] border border-[#21262d] rounded p-4"><p className="text-[10px] uppercase tracking-widest text-slate-500 font-mono">{label}</p><p className="text-xl mt-2">{value}</p></div>}
function Context({name,current,normal}:{name:string;current:number;normal?:number}){const d=normal?((current-normal)/normal*100):0;return <div className="bg-[#161b22] border border-[#21262d] rounded p-4"><p className="text-xs text-slate-500 font-mono">{name}</p><p className="text-xl mt-2">{current.toFixed(1)} <span className="text-xs text-slate-500">vs {normal?.toFixed(1)??'—'} normal</span></p>{normal&&<p className={`text-xs mt-1 ${d>0?'text-orange-300':'text-blue-300'}`}>{Math.abs(d).toFixed(0)}% {d>0?'above':'below'} normal</p>}</div>}
function Heatmap({hours}:{hours:Array<{time:string;cooling:number;heating:number}>}){const days=Array.from(new Set(hours.map(h=>h.time.slice(0,10))));return <div className="bg-[#161b22] border border-[#21262d] rounded p-4 overflow-x-auto"><h2 className="text-xs font-mono uppercase text-slate-500 mb-3">Hourly cooling-pressure heatmap</h2><div className="min-w-[720px] grid grid-cols-[60px_repeat(7,1fr)] gap-1"><div/>{days.map(d=><div key={d} className="text-center text-[10px] text-slate-500">{new Date(d+'T12:00').toLocaleDateString('en-US',{weekday:'short'})}</div>)}{[0,3,6,9,12,15,18,21].map(hr=><div key={hr} className="contents"><div className="text-[10px] text-slate-600">{hr}:00</div>{days.map(d=>{const h=hours.find(x=>x.time.startsWith(`${d}T${String(hr).padStart(2,'0')}`));const v=h?.cooling??0;return <div key={d} title={`${Math.round(v)}/100`} className="h-6 rounded" style={{background:`rgba(248,81,73,${.08+v/120})`}}/>})}</div>)}</div><p className="text-[10px] text-slate-600 mt-2">Darker cells indicate higher weather-driven cooling pressure; this is not measured demand.</p></div>}
