import { NextRequest, NextResponse } from 'next/server';
const hdd = (t: number) => Math.max(0, 65 - t); const cdd = (t: number) => Math.max(0, t - 65); const avg = (x:number[]) => x.length ? x.reduce((a,b)=>a+b,0)/x.length : 0;
export async function GET(req: NextRequest) {
  const q = req.nextUrl.searchParams; const lat = Number(q.get('lat')); const lon = Number(q.get('lon')); const dates = (q.get('dates') ?? '').split(',').filter(Boolean);
  if (!Number.isFinite(lat) || !Number.isFinite(lon) || !dates.length) return NextResponse.json({ error: 'Coordinates and forecast dates are required.' }, { status: 400 });
  const year = new Date().getUTCFullYear(); const params = new URLSearchParams({ latitude:String(lat), longitude:String(lon), start_date:`${year-10}-01-01`, end_date:`${year-1}-12-31`, daily:'temperature_2m_max,temperature_2m_min,precipitation_sum,shortwave_radiation_sum,et0_fao_evapotranspiration', temperature_unit:'fahrenheit', precipitation_unit:'inch', timezone:'auto' });
  try { const r = await fetch(`https://archive-api.open-meteo.com/v1/archive?${params}`, { next:{ revalidate:86400 } }); if (!r.ok) throw new Error(`Historical API returned ${r.status}`); const x = await r.json(); const d = x.daily; const monthDays = new Set(dates.map(v=>v.slice(5))); const byYear = new Map<number,{hdd:number;cdd:number;rain:number;ghi:number;et0:number}>();
    d.time.forEach((date:string,i:number)=>{ if (!monthDays.has(date.slice(5))) return; const y=Number(date.slice(0,4)); const row=byYear.get(y)??{hdd:0,cdd:0,rain:0,ghi:0,et0:0}; const mean=(d.temperature_2m_max[i]+d.temperature_2m_min[i])/2; row.hdd+=hdd(mean); row.cdd+=cdd(mean); row.rain+=d.precipitation_sum[i]??0; row.ghi+=(d.shortwave_radiation_sum[i]??0)/3.6; row.et0+=d.et0_fao_evapotranspiration[i]??0; byYear.set(y,row); }); const years=Array.from(byYear.entries()).map(([year,v])=>({year,...v})); return NextResponse.json({years,normal:{hdd:avg(years.map(v=>v.hdd)),cdd:avg(years.map(v=>v.cdd)),rain:avg(years.map(v=>v.rain)),ghi:avg(years.map(v=>v.ghi)),et0:avg(years.map(v=>v.et0))}});
  } catch(e){ return NextResponse.json({error:e instanceof Error?e.message:'Normals unavailable.'},{status:502}); }
}
